### ISSUE TITLE
linear_probing_hst.py: Calling resize with a float

### ISSUE THREAD

**Issue by holgerdell** [itu-algorithms/itu.algs4#2]
This line may call `_resize` with a float, but an integer is expected:

https://github.com/itu-algorithms/itu.algs4/blob/111366ba60400b8c69df26c6b25bc714e50630c9/itu/algs4/searching/linear_probing_hst.py#L170

Tasks:
- [x] Create a test case in `tests/` that exposes this error.
- [x] Fix this bug

**Comment by Andreas-Moller-Belsager** [comment]
I think a solution is to convert the float to an integer, and depending on whether you want to round up or down add 1.

**Comment by holgerdell** [comment]
`self.m // 2` would be an integer, always rounds down, and would be more correct than what's currently written there, so I would consider that an acceptable change. (However, there could be edge cases where rounding down is problematic - I do not have the time right now to investigate - so a unit test for this data structure would be useful.)

**Comment by Andreas-Moller-Belsager** [comment]
That is also what i have done for now
