### ISSUE TITLE
A question about RedBlackBST.

### ISSUE THREAD

**Issue by YRFT** [itu-algorithms/itu.algs4#7]
https://github.com/itu-algorithms/itu.algs4/blob/master/itu/algs4/searching/red_black_bst.py

There are two implementations of balance in RedBlackBST. One in put method and another in balance method.

In put method we perform "rotate left" only if the left child is black and the right child is red. That's ok because if both children are red, we do not need "rotate". We can just perform "color flip" to raise the middle node up.

But in balance method, we do "rotate left" if the right child is red and do not check the left child. I can't figure out why we don't check the left child. In the current implementation if both children are red, we will do some useless work, because "rotate left" then "rotate right" will not change the tree. In my opinion, we should check the left child as we did in put method to save some work.

I have modified the code in balance method to include the check for the left child and run some tests with the "check" method in booksite. All the tests have been passed.

I have been confused for several days and appreciate any feedback. Thank you.

**Comment by thorehusfeldt** [comment]
1. The first answer is that our Python implementation is merely a (rather faithful) translation of the Java implementation by Sedgewick and Wayne; the current version is here:

[https://algs4.cs.princeton.edu/33balanced/RedBlackBST.java.html](https://algs4.cs.princeton.edu/33balanced/RedBlackBST.java.html)

The corresponding place in Kevin’s repo is at https://github.com/kevin-wayne/algs4/blob/e9b520b8a0395a7b28690eeb10e79f369ecf05ff/src/main/java/edu/princeton/cs/algs4/RedBlackBST.java#L407 

2. The next question is why the java implementation doesn’t check the left child’s colour to avoid some redundant restructuring. My honest answer is that I don’t know. I _suspect_ that you are right. If so: well done. The most constructive next step is to raise the issue on Kevin’s repository.

3. One of the design constraints in our Python translations is that we aim to stay in sync with the Java originals, to minimise confusion. Thus, the issue _here_ will only be fixed when it is acknowledged and fixed _there_. I will therefore mark it as “won’t fix” but keep it open.

**Comment by YRFT** [comment]
I really appreciate your replay. It's very helpful to me.

I have just created a pull request to Kevin’s repo https://github.com/kevin-wayne/algs4/pull/101/commits/b2224bfc4ac8fa157addfbbbcfa64b99bfd926e2.

I will pay attention to the pull request and update this issue to reflect the result of the pull request to let you easy to know will the pull request be merged.

**Comment by YRFT** [comment]
The `balance` method has been optimized in https://github.com/kevin-wayne/algs4/commit/5729bbb742f985ece102c2d3074421eb2d5e42c2.

Again, thank you for your suggestion.

**Comment by holgerdell** [comment]
@YRFT Thanks! Would you like to send us a pull request with the update in python as well?

**Comment by YRFT** [comment]
I'm very glad to do it. I have just created a pull request.
